#!/bin/sh

# This script was created August 8, 2013 by Luke Johnston to backup
# folders which are used for work (i.e. SAS, R, bin, .emacs.d, and Documents)
# on a weekly basis using crontab (a symlink is put in cron.weekly)

# Updated on 2014-04-21 by Luke. Removed references to Ubuntu One, as it will
# be discontinued.

# Script variables
DATE=$(date +"%F") # The %F stands for YYYY-MM-DD
OUTDIR=/home/luke/Dropbox/Luke/backups
BAK_DIR=/home/luke/archive/backups

# Running tar
cd /home/luke/
tar cvpzf $OUTDIR/workBackup-$DATE.tgz \
    --exclude=Documents/bibliography/styles \
    --exclude=bin/anaconda \
    --exclude=bin/jdk \
    --exclude=bin/VUE \
    --exclude=bin/docear \
    --exclude=SAS/depot \
    --exclude="Documents/my games" \
    --exclude=R/x86_64-pc-linux-gnu-library \
    Documents \
    bin \
    R \
    org \
    Templates \
    .myconfig

# Delete all backups older than 8 days
find $OUTDIR/workBackup* -mtime +8 -delete

cp $OUTDIR/workBackup-$DATE.tgz $BAK_DIR/

