#!/bin/sh

# This script was created August 12, 2013 by Luke Johnston to backup
# all home folders and files, but not including folders backed up by the
# script "backup-work" (i.e. Documents, SAS, and R). Backups occur
# on a monthly basis using crontab (a symlink is put in cron.monthly)

# Updated on 2014-04-21 by Luke to remove moving backups to Ubuntu One,
# as the service will no longer be provided.

# Script variables
DATE=$(date +"%F") # The %F stands for YYYY-MM-DD
OUTDIR=/home/luke/Dropbox/Luke/backups
BAK_DIR=/home/luke/archive/backups

# Running tar
cd /home/
tar cvpzf $OUTDIR/homeBackup-$DATE.tgz \
    --exclude=luke/.gem \
    --exclude=luke/.TelegramDesktop \
    --exclude=luke/.misc \
    --exclude=luke/.mozilla/firefox/iznlunfz.default/storage \
    --exclude="luke/Larian Studios" \
    --exclude=luke/archive \
    --exclude=luke/Music \
    --exclude=luke/Downloads \
    --exclude=luke/Dropbox \
    --exclude=luke/.local/share \
    --exclude=luke/Documents \
    --exclude=luke/SAS \
    --exclude=luke/bin \
    --exclude="luke/My Games" \
    --exclude=luke/org \
    --exclude=luke/.PlayOnLinux \
    --exclude=luke/R/x86_64* \
    --exclude=luke/.thunderbird/0atvmpgk.default/ImapMail \
    --exclude=luke/.thunderbird/0atvmpgk.default/extensions/{e2fda* \
    --exclude=luke/.dropbox-dist \
    --exclude=luke/.dropbox \
    --exclude=luke/.cache \
    --exclude=luke/.cabal \
    --exclude=luke/.config/packrat \
    --exclude=luke/.TelegramDesktop/tdata \
    --exclude=luke/.wine \
    luke/

# Delete all backups older than 1 month
find $OUTDIR/homeBackup* -mtime +31 -delete

cp $OUTDIR/homeBackup-$DATE.tgz $BAK_DIR/

